config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  root 'pictures#index'

  resources :pictures

  post 'pictures/:id' => 'pictures#create_comment', as: 'create_comment'
  get 'pictures/user/:id' => 'pictures#user', as: 'pictures_user'

  devise_for :users

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  has_many :notes

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", origin: "500x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
  has_many :pictures
  has_many :notes

  after_create { |user| user.send_reset_password_instructions }
  def password_required?
    new_record? ? false : super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.paginate(page: params[:page], per_page: 2)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    if @picture.save
      redirect_to @picture
    else
      render 'new'
    end

  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update(picture_params)
      redirect_to @picture
    else
      render 'edit'
    end
  end

  def show
    @picture = Picture.find(params[:id])
    @note = Note.new
    @notes = Note.all
    @average = average_rate(@picture)
  end

  def create_comment
    @note = current_user.notes.build(comment_params)
    if @note.save
      redirect_to root_path
    end
  end

  def user
    @user = User.find(params[:id])
  end

  def average_rate(picture)
    counter = 0
    rate = 0
    picture.notes.each do |note|
      counter += 1
      rate += note.rate.to_f
    end
    if rate == 0
      average = 0
    else
      average = rate/counter
    end
    return average
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :image, :user_id)
  end

  def comment_params
    params.require(:note).permit(:description, :rate, :user_id, :picture_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/admin/users/_chart.html.erb
<h1>Pribet</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/application/navbar' %>

<div class="container">

  <div class="row">
    <div class="col-sm-3">
      <div class="panel panel-default" id="cart">
        <div class="panel-heading">
          <h3 class="panel-title">Galleries of users</h3>
        </div>
        <div class="panel-body">
          <ul>
            <% User.all.each do |user| %>
                <li><%= link_to user.name, pictures_user_path(user) %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% if user_signed_in? %>
          <div class="col-sm-3">
            <%= link_to 'Add new photo', new_picture_path, class: 'btn btn-success' %>
          </div>
      <% end %>
    </div>


    <div class="col-sm-9">

      <% flash.each do |type, message| %>
          <%= content_tag :div, message, class: "alert alert-#{type}" %>
      <% end %>

      <%= yield %>

    </div>

  </div>



</div>


</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if current_user.admin? %>
                      <li><%= link_to 'Admin Panel', admin_root_path %></li>
                  <% end %>
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li><a href="#">View orders</a></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/pictures/_form.html.erb
<%= form_for @picture, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group">
        <%= f.label :title, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group">
      <%= f.label :image, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.file_field :image, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/pictures/edit.html.erb
<h1>Edit picture </h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<div class="row">
  <div class="col-sm-12 products-pagination">
    <%= will_paginate @pictures %>
  </div>
</div>

<% @pictures.each do |picture| %>

  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= link_to picture.title, picture_path(picture) %></h3>
        <div class="img">
          <%= image_tag picture.image.url(:medium) %>
        </div>
        <h4>By: <%= picture.user.name %></h4>
      </div>
    </div>
  </div>

<% end %>


<br/>

<%= link_to 'edit password', edit_user_password_path %>

app/views/pictures/new.html.erb
<h1>Add new photo</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="row">
    <div class="col-sm-6 product-item">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1><%= @picture.title %></h1>
        </div>
        <div class="panel-body">

            <%= image_tag @picture.image.url(:origin) %>
          <h3>Average score: <%= @average.to_f %></h3>

          <h4>By: <%= @picture.user.name %></h4>
        </div>
      </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
      <% if user_signed_in? %>
          <%= form_for @note, :url => { :action => 'create_comment', html: {class: 'form-horizontal'} } do |f| %>
              <%= f.hidden_field :picture_id, :value => @picture.id %>


              <div class="form-group">
                <%= f.label 'Rate photo' %>
                <%= f.select :rate, (1..5), class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label 'Add your comment:' %>
                <div class="col-sm-10">
                    <%= f.text_area :description %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-10">
                    <%= f.submit 'Comment', class: 'btn btn-default' %>
                </div>
              </div>

          <% end %>
      <% end %>
    </div>
</div>

<hr/>

<div class="ro">
  <div class="col-sm-6">
        <% @notes.each do |note| %>
            <% if note.picture_id == @picture.id %>

                <div class="panel panel-default">
                  <div class="panel-heading"> by: <%= note.user.name %> <br/> score: <%= note.rate %></div>
                  <div class="panel-body">
                    <%= note.description %>
                  </div>
                </div>
            <% end %>
        <% end %>
  </div>
</div>


<hr/>

app/views/pictures/user.html.erb
<h1><%= @user.name %>'s page</h1>

<diw class="row">
  <% @user.pictures.each do |picture| %>
      <diw class="col-sm-6">

            <div class="panel panel-default">
              <div class="panel-heading">
                <h1><%= link_to picture.title, picture_path(picture) %></h1>
              </div>
              <div class="panel-body">
                <div class="img">
                  <%= image_tag picture.image.url(:medium) %>
                </div>
              </div>
            </div>

      </diw>
  <% end %>
</diw>